version: "1.0"
stages:
  - Init
  - Validate
steps:
  main_clone:
    type: git-clone
    title: Cloning git repository
    stage: Init
    arguments:
      repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
      git: github
      revision: "${{CF_REVISION}}"
  pre_commit:
    type: rothandrew/pre-commit
    title: Validating pre-commit hooks
    stage: Validate
