version: "1.0"
stages:
  - Init
steps:
  main_clone:
    title: Cloning repository
    stage: Init
    type: git-clone
    arguments:
      repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
      git: github
      revision: "${{CF_REVISION}}"
  parallel_tests:
    title: Running tests
    stage: test
    type: parallel
    steps:
      docker_build:
        title: Ensuring docker image is buildable
        type: build
        image_name: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
        tag: "${{CF_REVISION}}"
        working_directory: "${{main_clone}}/src/docker"
      validate_pre_commit:
        title: Running pre-commit validations
        type: freestyle
        image: "dadsgarage/dadsgarage:0.2.2"
        commands:
          - pre-commit install
          - pre-commit run -a
